### ISSUE TITLE
gosspks not showing packages list

### ISSUE THREAD

**Issue by digitalbox94** [jdel/gosspks#6] opened 2019-11-11 12:01 UTC
Hello,

I've installed gosspks on Ubuntu and I've got it working when requesting "about" or "models"

./gosspks-linux-amd64 --port 80
curl -i localhost:80/about
{"name":"gosspks","version":"v0.1.2","maintainer":"jdel","license":"GNU GPL v3","year":2018}

 curl -i localhost:80/v1/models
-> Ok displaying all the models

However when trying to retrieve the list of packages I have the below error : 
curl -i localhost:80/v1/packages
HTTP/1.1 404 Not Found
Date: Mon, 11 Nov 2019 12:00:41 GMT
Content-Length: 0
Content-Type: text/plain; charset=utf-8

Any idea about this issue ?

**Comment by jdel** [comment] 2019-11-12 14:04
Hello, 

Typically, 404 is returned when there is no packages to show. Have you placed packages in the right directory ?

**Comment by digitalbox94** [comment] 2019-11-12 22:17
I've put a unique package named "icecast_braswell-6.1_2.4.4-2.spk" in $HOME/gosspks/packages/

However to launch successfully gossks server, I have to use sudo :
sudo gosspks-linux-amd64 --port 80

(If no "sudo" and launched with current user, I have an error message "FATA[19/11/12 23:15:50.706] listen tcp :80: bind: permission denied       module=cmd/cmd.go")

**Comment by jdel** [comment] 2019-11-13 13:37
It is normal that bind is refused to unprivileged users for ports in the 1-1024 range if i remember correctly.

In any case, i would recommend you run `gosspks` on another port and use a reverse proxy to handle TLS as this is not implemented in `gosspks`

Regarding your package, is it built to synology specs ? 

could you download any package you like from https://packages.jdel.org/api/v1/packages and put it in `$HOME/gosspks/packages/` ?

Also, please run with `-l debug` in order to get more detailed logs.

**Comment by digitalbox94** [comment] 2019-11-13 18:57
Ok got it working by renaming the file, thanks for the hints. I currently use SSPKS where this kind of filename is not an issue, whereas for GoSSPKS it is. So maybe something to improve or to indicate as limitation in the documentation :)

Good filename : icecast_braswell-2.4.4-2.spk
Wrong filename : icecast_braswell-6.1_2.4.4-2.spk

Additional question : I'm currently hosting a personal SSPKS repo which only requires PHP to be activated on the host machine.  If I understand, GoSSPKS will require "gosspks-linux-amd64" binary to have the repo hosted on a machine ?

I'm asking this because SSPKS can be installed on many personal websites which propose PHP extensions (like free.fr), whereas GoSSPKS is more limited from this point of view. In the other hand, a current limitation I can see on SSPKS is the memory limit due to PHP (I've compiled an Erlang package which can only be downloaded outside of SSPKS due to its big size)

**Comment by jdel** [comment] 2019-11-14 13:44
Thanks for reporting your use case. `gosspks` has been my project to learn golang and i am aware it is far from perfect. However i did aim at implementing all functionalities of `sspks` so anything missing is most likely not intended. 

I have some plans for gosspks but i'm lacking the time needed so i can't guarantee a fix for this anytime soon. Please open another ticket regarding the naming problem including a debug log with both names so this issue doesn't go under the radar.

The issue with sspks however, if you can assist with the debugging i'm happy to put in the fix but i don't really have interest in debugging php anymore. Have you experienced the same behavior with `gosspks` ?

Regarding the technology change, yes, `gosspks` is compiled as an almost static binary and only depends no `glibc` which most linux will have. The advantage is that it can run anywhere with virtually no dependency, but you need a server to run it. there are plenty of cheap providers for virtual servers or docker workloads that would work well. Unfortunately, if you rely on mutualized hosting then you might be stuck with `sspks`.

Also bear in mind that `gosspks` does not come with a user interface, but merely an API responding to synology devices.

**Comment by DigitalBox98** [comment] 2019-11-14 20:01
Ok thanks for all this information - especially on Virtual Private Server. I will create a dedicated ticket for the naming issue.

**Comment by DigitalBox98** [comment] 2019-11-14 20:11
Checking again, I didn't reproduce naming issue with gosspks (it seems initial issue was relative to using port <1024, so using port above this value is fine). I still only have one issue with a specific package, I will raise another ticket:)

**Closed** 2019-11-24 10:55 UTC
